version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ADVERTISED_LISTENERS: 0.0.0.0
      KAFKA_CREATE_TOPICS: "simpletest"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:                                                                                                                                                                                                
      - /var/run/docker.sock:/var/run/docker.sock
